### PR TITLE
Fix missing styles with View Transitions

### PR DESCRIPTION
**Pull request by lilnasy**
https://github.com/thomasledoux1/website-thomas-astro/assets/69170106/5797b7b3-8ed4-4d67-ba44-24008622ca22

### CODE REVIEW

**Comment by ref-thomasledoux1** [comment]
Hi @lilnasy the build is failing with the following error:



src/pages/blog/tags/[...slug].astro:58:15 - error ts(2322): Type '{ minutesRead: any; post: ({ id: "adding-comments-prisma-planetscale-astro-vercel-edge.mdx"; slug: "adding-comments-prisma-planetscale-astro-vercel-edge"; body: string; collection: "blog"; data: { ...; }; } & { ...; }) \| ... 23 more ... \| ({ ...; } & { ...; }); index: number; }' is not assignable to type 'IntrinsicAttributes & Props'.
16:38:59.134 | Property 'minutesRead' does not exist on type 'IntrinsicAttributes & Props'.
16:38:59.134 |  
16:38:59.134 | 58               minutesRead={remarkPluginFrontmatter?.minutesRead}
16:38:59.134 | ~~~~~~~~~~~
16:38:59.134

<br class="Apple-interchange-newline">

**Comment by lilnasy** [comment]
Looks like that file needs the same refactor as `blog/index.astro`.

**Comment by ref-thomasledoux1** [comment]
@lilnasy do you think I can re-add the Vercel adapter to see if it works on there now with the changes merged (I also adapted blog/tags/[...slug].astro

**Comment by lilnasy** [comment]
Yes, the adapter would not factor into the bug. It is just easier to test locally with the node adapter.

**Pull request merged**
